### PR TITLE
CFE-1103: UPSTREAM: <carry>: Update admins to add CFE members

### PR DESCRIPTION
**Pull request by oceanc80**
**Description of the change:**
Clean up owners file:
- Remove external and emeritus admins
- Add CFE team members

**Motivation for the change:**
Allow CFE team members to approve and merge PRs

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm
/approve

**Comment by chiragkyal** [comment]
Will this change going to cause any conflict while rebasing?

**Review by grokspawn — APPROVED** [review]

**Comment by oceanc80** [comment]
> Will this change going to cause any conflict while rebasing?

We might need to use the upstream carry notation in the PR title to ensure that it won't conflict.

**Comment by arkadeepsen** [comment]
> > Will this change going to cause any conflict while rebasing?
> 
> We might need to use the upstream carry notation in the PR title to ensure that it won't conflict. Although it looks like syncing from upstream has been done via merging, so I think this change should be fine as is and will just overwrite what was pulled from upstream.

@oceanc80  Do we also need to add `UPSTREAM: <carry>:` in the commit message?

**Comment by arkadeepsen** [comment]
Adding the label as PR does not contain any code changes
/label qe-approved

**Pull request merged**
