### PR TITLE
CFE-1114: UPSTREAM: <carry>: Bump kubernetes.core to v2.4.2

### PR DESCRIPTION
**Pull request by chiragkyal**
**Description of the change:**

- Update `openshift/release/ansible/requirements.yml` file to use kubernetes.core v2.4.2
- Run `openshift/release/ansible/update-collections.sh` script to update the vendored collections
- Update `openshift/ci/testdata/ansible/memcached-operator/requirements.yml` to use kubernetes.core v2.4.2 in order to match with the downstream image dependencies. 

**Motivation for the change:**
In favour of 

- https://github.com/openshift/ocp-release-operator-sdk/pull/374
- https://github.com/openshift/ocp-release-operator-sdk/blob/d147fd3b63cf4a6bc4c1d9168f5388f2da102505/release/ansible/requirements.yml#L5-L6

### CODE REVIEW

**Comment by chiragkyal** [comment]
/hold 
for https://github.com/openshift/ansible-operator-plugins/pull/12

**Comment by chiragkyal** [comment]
We need to address https://github.com/openshift/ansible-operator-plugins/pull/12#discussion_r1716572263 here

**Comment by arkadeepsen** [comment]
/lgtm cancel
Until https://github.com/openshift/ansible-operator-plugins/pull/6#issuecomment-2288335271 is addressed.

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved

**Comment by chiragkyal** [comment]
/unhold
https://github.com/openshift/ansible-operator-plugins/pull/6#issuecomment-2288335271 is addressed

**Pull request merged**
